### ISSUE TITLE
WebUI auth session not working

### ISSUE THREAD

**Issue by jalbright-active** [Flipkart/HostDB#8]
I can successfully log in using the default admin account.  However, when I attempt to add a host or tag, I get the following error in the browser:  

Session token seems to be corrupted Ciphertext does not begin with a valid header for 'salt' header mode.

The server log shows this:

2015/01/07 16:32:40 FATAL> Session.pm:49 HostDB::Session::validate_session - 4012: Session token seems to be corrupted Ciphertext does not begin
 with a valid header for 'salt' header mode at /usr/local/share/perl5/HostDB/Session.pm line 48.
2015/01/07 16:32:40 FATAL> Session.pm:49 HostDB::Session::validate_session -  at /usr/local/share/perl5/HostDB/Session.pm line 49.
2015/01/07 16:32:40 FATAL> Session.pm:49 HostDB::Session::validate_session -    HostDB::Session::validate_session(undef, "10.12.0.144") called a
t /var/www/cgi-bin/hostdb_rest.fcgi line 132
2015/01/07 16:32:40 FATAL> Session.pm:49 HostDB::Session::validate_session -    eval {...} called at /var/www/cgi-bin/hostdb_rest.fcgi line 131

This occurs both on a custom installation I performed on RHEL as well as a test installation I performed on Debian using the provided install scripts.

**Comment by hostdb** [comment]
Is the cookie "HostDB" getting set correctly? Is it passed to the API call?

PS: This auth part is really unnecessary. I should rewrite it with basic
http auth. Not getting time though.

~jain

**Comment by jalbright-active** [comment]
It looks like the HostDB response cookie is not being set properly.  I see the response cookie data come through when authenticating, but it is not actually persistent.  This was tested in Chrome, IE and Firefox.

**Comment by jainmjo** [comment]
Have you set the cookie domain in index.html and server_conf.yaml?

------------------------------------------------------
Setup complete.
Configure SSL in /etc/apache2/sites-enabled/hostdb
Configure cookie domain name in /var/www/hostdb/index.html:317 and
/etc/hostdb/server_conf.yaml
Goto https://hostdb-test.nm.flipkart.com and login with creds admin:secret
The UI is crap and buggy. Install client and use the CLI.
------------------------------------------------------

**Comment by jalbright-active** [comment]
I did set the cookie domain in both of those files.

The portion I modified in index.html begins with:  $.removeCookie('HostDB', 

For some reason, though, I see that the domain in the response cookie data is still "yourdomain.com".

**Comment by jainmjo** [comment]
yourdomain.com is coming from /etc/hostdb/server_conf.yaml. Restart apache
after modifying it.

~jj

**Comment by jalbright-active** [comment]
I restarted apache and the response cookie data is now showing the correct domain.  However, I am still experiencing the same issue with the cookie not being set and the error being generated.

**Comment by jainmjo** [comment]
Did you try clearing the old cookies?

**Comment by jalbright-active** [comment]
There are no cookies for this domain.  That is the problem.  I get the cookie data in the response from v1/Auth when logging in, but the cookie doesn't actually get created for some reason.  I did create a cookie manually using the response cookie data, and this worked.  I just don't know why the cookie is being created automatically.

**Comment by jalbright-active** [comment]
I found the issue.  The cookie was being ignored because it is being set as secure, and I was testing HostDB using a non-secure session.  Everything seems to be working now after changing hostdb_rest.fcgi so that the cookie is not marked secure.
